# Generated by Django 4.0.5 on 2022-06-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('job_details', models.CharField(blank=True, max_length=50)),
                ('job_details1', models.CharField(blank=True, max_length=50)),
                ('job_details2', models.CharField(blank=True, max_length=50)),
                ('job_details3', models.CharField(blank=True, max_length=50)),
                ('job_details4', models.CharField(blank=True, max_length=50)),
                ('job_details5', models.CharField(blank=True, max_length=50)),
                ('job_details6', models.CharField(blank=True, max_length=50)),
                ('job_details7', models.CharField(blank=True, max_length=50)),
                ('image_source', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source6', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source7', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source8', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source9', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source10', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source11', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source12', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source13', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source14', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source15', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
