# Generated by Django 4.0.5 on 2022-06-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_source',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source10',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source11',
            new_name='image10',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source12',
            new_name='image11',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source13',
            new_name='image12',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source14',
            new_name='image13',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source15',
            new_name='image14',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source2',
            new_name='image15',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source3',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source4',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source5',
            new_name='image4',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source6',
            new_name='image5',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source7',
            new_name='image6',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source8',
            new_name='image7',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_source9',
            new_name='image8',
        ),
        migrations.AddField(
            model_name='project',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
