# Generated by Django 4.0.5 on 2022-09-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
