# Generated by Django 4.0.5 on 2022-06-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('benefits', models.CharField(blank=True, max_length=50)),
                ('benefits1', models.CharField(blank=True, max_length=50)),
                ('benefits2', models.CharField(blank=True, max_length=50)),
                ('benefits3', models.CharField(blank=True, max_length=50)),
                ('benefits4', models.CharField(blank=True, max_length=50)),
                ('benefits5', models.CharField(blank=True, max_length=50)),
                ('benefits6', models.CharField(blank=True, max_length=50)),
                ('benefits7', models.CharField(blank=True, max_length=50)),
                ('benefits8', models.CharField(blank=True, max_length=50)),
                ('benefits9', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
